### ISSUE TITLE
API Auth Google

### ISSUE THREAD

**Issue by ohthias** [ohthias/Astro-reimagination#7]

**Comment by Nikolls06** [comment]
eu nao sabo usa github

**Comment by Nikolls06** [comment]
links sobre a implementação do login google :
https://console.firebase.google.com/?hl=p
https://www.youtube.com/watch?v=92RkvBuIcts
https://console.cloud.google.com/cloud-resource-manager

**Comment by Nikolls06** [comment]
API Spotify: 
https://www.youtube.com/watch?v=zQKrgXsZFSE -- consumindo api em java
https://developer.spotify.com/documentation/web-api
